# Generated by Django 3.1.7 on 2021-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210224_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Genres',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='gender',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movie.Genres'),
        ),
    ]
